using System.Linq;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Content.Shared.Shuttles.Components.ShipyardConsoleComponent;

namespace Content.Client._Eclipse.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardConsoleWindow : FancyWindow,
    IComputerWindow<ShipyardConsoleBoundUserInterfaceState>
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private readonly IGameTiming _timing;
    private List<ShuttlePrototype> _shuttles = new();
    private string? _selectedFilter;

    public ShipyardConsoleWindow()
    {
        _timing = IoCManager.Resolve<IGameTiming>();
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    private void PopulateCategories()
    {
        Categories.Clear();

        var categories = _shuttles.Select((x) => x.Category).Distinct();

        foreach (var entry in categories)
        {
            Categories.AddItem(Loc.GetString(entry), metadata: entry.Id);
        }
    }

    private void PopulateShuttles(ComputerBoundUserInterfaceBase cb)
    {
        PurchasableShuttles.RemoveAllChildren();

        if (_selectedFilter == null)
            return;

        foreach (var entry in _shuttles)
        {
            if (entry.Category == _selectedFilter)
            {
                var canPurchase = true;
                var shuttleEntry = new ShuttleRow
                {
                    Shuttle = entry,
                    ShuttleName = { Text = Loc.GetString(entry!.Name) },
                    Purchase = { Text = Loc.GetString("shipyard-console-window-purchase-available"), Disabled = !canPurchase },
                    Price = { Text = "1$" },
                };

                shuttleEntry.Purchase.OnConfirming += OnConfirmingPurchase;
                shuttleEntry.Purchase.OnPressed += (args) =>
                {
                    if (_currentlyConfirmingButton != null)
                        _currentlyConfirmingButton.ClearConfirmation();
                    _currentlyConfirmingButton = null;

                    ShipyardConsolePurchaseMessage msg = new()
                    {
                        ShuttleId = entry.ID,
                    };

                    cb.SendMessage(msg);
                };

                PurchasableShuttles.AddChild(shuttleEntry);
            }
        }
    }

    private ConfirmButton? _currentlyConfirmingButton;

    private void OnConfirmingPurchase(ButtonEventArgs args)
    {
        if (args.Button is not ConfirmButton confirmButton)
            return;

        if (_currentlyConfirmingButton != null)
            _currentlyConfirmingButton.ClearConfirmation();
        _currentlyConfirmingButton = confirmButton;
    }

    public void SetupComputerWindow(ComputerBoundUserInterfaceBase cb)
    {
        IdButton.OnPressed += _ => cb.SendMessage(new ItemSlotButtonPressedEvent(IdCardSlotId));

        _shuttles = _prototypeManager.EnumeratePrototypes<ShuttlePrototype>().ToList();
        _shuttles.Sort((x, y) => string.Compare(x.Name, y.Name, StringComparison.CurrentCulture));

        Categories.OnItemSelected += args =>
        {
            var entry = Categories[args.ItemIndex];

            if (entry.Metadata is not string category)
                return;

            _selectedFilter = category;
            PopulateShuttles(cb);
        };

        PopulateCategories();
    }

    public void UpdateState(ShipyardConsoleBoundUserInterfaceState state)
    {
        IdButton.Text = state.IsIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        /*
        if (_earlyLaunchTime == null)
        {
            Countdown.Text = "00:10";
        }
        else
        {
            var remaining = _earlyLaunchTime.Value - _timing.CurTime;

            if (remaining < TimeSpan.Zero)
                remaining = TimeSpan.Zero;

            Countdown.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
        }*/
    }
}
