using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Shuttles.Prototypes;

namespace Content.Client._Eclipse.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleRow : PanelContainer
{
    public ShuttlePrototype? Shuttle;
    public ShuttleRow()
    {
        RobustXamlLoader.Load(this);
    }
}
