- type: job
  id: FrontierJanitor
  name: job-name-frontier-janitor
  description: job-description-frontier-janitor
  playTimeTracker: JobFrontierJanitor
  icon: JobIconJanitor
  startingGear: FrontierJanitorGear
  supervisors: job-supervisors-sr
  access:
  - FrontierJanitor
  - Maintenance
  - External
  #special:
  #- !type:GiveItemOnHolidaySpecial
  #  holiday: GarbageDay
  #  prototype: WeaponRevolverInspector

- type: startingGear
  id: FrontierJanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: FrontierJanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: FrontierJanitorChameleonOutfit
  job: FrontierJanitor
  equipment:
    head: ClothingHeadHatPurplesoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterWinterJani
    gloves: ClothingHandsGlovesJanitor

- type: entity
  parent: JanitorPDA
  id: FrontierJanitorPDA
  components:
  - type: Pda
    id: FrontierJanitorIDCard
