using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Eclipse.StoreVendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class StoreVendingMachineItem : BoxContainer
{
    public StoreVendingMachineItem(EntProtoId entProto, string text)
    {
        RobustXamlLoader.Load(this);

        ItemPrototype.SetPrototype(entProto);

        NameLabel.Text = text;
    }

    public void SetText(string text)
    {
        NameLabel.Text = text;
    }
}
