using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Robust.Client.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Shared.IdentityManagement;
using Robust.Client.Graphics;
using Robust.Shared.Utility;
using Content.Shared.StoreVendingMachines.Components;

namespace Content.Client._Eclipse.StoreVendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class StoreVendingMachineMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly Dictionary<EntProtoId, EntityUid> _dummies = [];
    private readonly Dictionary<EntProtoId, (ListContainerButton Button, StoreVendingMachineItem Item)> _listItems = new();

    /// <summary>
    /// Whether the vending machine is able to be interacted with or not.
    /// </summary>
    private bool _enabled;

    public event Action<GUIBoundKeyEventArgs, ListData>? OnItemSelected;

    public StoreVendingMachineMenu()
    {
        MinSize = SetSize = new Vector2(250, 150);
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        VendingContents.SearchBar = SearchBar;
        VendingContents.DataFilterCondition += DataFilterCondition;
        VendingContents.GenerateItem += GenerateButton;
        VendingContents.ItemKeyBindDown += (args, data) => OnItemSelected?.Invoke(args, data);
    }

    /// <summary>
    /// Populates the list of available items on the vending machine interface
    /// and sets icons based on their prototypes
    /// </summary>
    public void RefreshInventory(EntityUid uid)
    {
        _listItems.Clear();

        if (!_entityManager.TryGetComponent<StoreVendingMachineComponent>(uid, out var comp))
        {
            _enabled = false;
            return;
        }

        if (!_prototypeManager.TryIndex(comp.InventoryId, out var inventoryProto))
        {
            _enabled = false;
            return;
        }

        _enabled = !comp.Ejecting;

        var longestEntry = string.Empty;
        var listData = new List<StoreVendorItemsListData>();

        foreach (var (id, entry) in inventoryProto.Inventory)
        {
            if (!_prototypeManager.Resolve(id, out var prototype))
            {
                continue;
            }

            if (!_dummies.TryGetValue(id, out var dummy))
            {
                dummy = _entityManager.Spawn(id);
                _dummies.Add(id, dummy);
            }

            var itemName = Identity.Name(dummy, _entityManager);
            var itemText = $"{itemName} [${entry.Price}]";

            if (itemText.Length > longestEntry.Length)
                longestEntry = itemText;

            listData.Add(new StoreVendorItemsListData(prototype.ID)
            {
                ItemText = itemText,
            });
        }

        VendingContents.PopulateList(listData);

        SetSizeAfterUpdate(longestEntry.Length, inventoryProto.Inventory.Count);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        // Don't clean up dummies during disposal or we'll just have to spawn them again
        if (!disposing)
            return;

        // Delete any dummy items we spawned
        foreach (var entity in _dummies.Values)
        {
            _entityManager.QueueDeleteEntity(entity);
        }
        _dummies.Clear();
    }

    private bool DataFilterCondition(string filter, ListData data)
    {
        if (data is not StoreVendorItemsListData { ItemText: var text })
            return false;

        if (string.IsNullOrEmpty(filter))
            return true;

        return text.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
    }

    private void GenerateButton(ListData data, ListContainerButton button)
    {
        if (data is not StoreVendorItemsListData { ItemProtoID: var protoID, ItemText: var text })
            return;

        var item = new StoreVendingMachineItem(protoID, text);
        _listItems[protoID] = (button, item);
        button.AddChild(item);
        button.AddStyleClass(StyleClass.ButtonSquare);
        button.Disabled = !_enabled;
    }

    private void SetSizeAfterUpdate(int longestEntryLength, int contentCount)
    {
        SetSize = new Vector2(Math.Clamp((longestEntryLength + 2) * 12, 250, 400),
            Math.Clamp(contentCount * 50, 150, 350));
    }
}

public record StoreVendorItemsListData(EntProtoId ItemProtoID) : ListData
{
    public string ItemText = string.Empty;
}

