using Robust.Client.AutoGenerated;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Bank.BUIStates;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Bank;

namespace Content.Client._Eclipse.Bank.UI;

[GenerateTypedNameReferences]
public sealed partial class ATMWindow : FancyWindow
{
    public event Action? OnDeposit;
    public event Action<uint>? OnWithdraw;

    public ATMWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DepositButton.OnPressed += _ =>
        {
            OnDeposit?.Invoke();
        };
        WithdrawButton.OnPressed += _ =>
        {
            if (uint.TryParse(WithdrawLineEdit.Text, out var amount) && amount > 0)
            {
                OnWithdraw?.Invoke(amount);
                WithdrawLineEdit.Text = "";
            }
            else
            {
                ResultLabel.Text = Loc.GetString("atm-window-invalid-amount");
            }

        };
    }

    public void UpdateState(ATMBoundUserInterfaceState state)
    {
        if (state.MoneyUpdated)
        {
            if (state.Money.HasValue)
                BalanceLabel.Text = Loc.GetString("atm-window-balance", ("amount", state.Money.Value));
            else
                BalanceLabel.Text = Loc.GetString("atm-window-no-account");
        }

        if (state.ResultMessage.HasValue)
            ResultLabel.Text = Loc.GetString(state.ResultMessage.Value);

        if (state.MoneyInserted.HasValue)
            InsertedLabel.Text = Loc.GetString("atm-window-inserted-cash", ("amount", state.MoneyInserted.Value));
        else
            InsertedLabel.Text = Loc.GetString("atm-window-no-cash-inserted");
    }
}
