- type: roleLoadout
  id: JobHeadOfSectorSecurity
  groups:
  - HeadofSecurityHead
  - HeadofSecurityNeck
  - HeadofSecurityJumpsuit
  - SecurityBackpack
  - SecurityBelt
  - HeadofSecurityOuterClothing
  - SecurityShoes
  - SurvivalSecurity
  - Trinkets
  - HeadofSecurityJobTrinkets
  - GroupSpeciesBreathToolSecurity
